language: php

php:
  - 5.6

sudo: false

services:
  - mysql

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --dev --prefer-dist --no-interaction
# codeception
  - travis_retry composer global require "codeception/codeception=2.0.*" "codeception/specify=*" "codeception/verify=*"
# setup application:
  - |
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" config/web.php
    cd tests
    codecept build
before_script:
  - mysql -e 'CREATE DATABASE team_test;';
script:
  - |
    cd ..
    php -S localhost:8080 > /dev/null 2>&1 &
    curl 'http://localhost/'
    cd ../tests
    codecept run
